# Generated by Django 6.0.6 on 2026-07-04 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_type', models.CharField(choices=[('AUDIO_TO_SIGN', 'Audio to Sign Language'), ('SIGN_TO_AUDIO', 'Sign Language to Audio')], max_length=20)),
                ('input_text', models.TextField(help_text='Spoken phrase or detected gesture')),
                ('output_result', models.TextField(help_text='Matched ISL animation or spoken audio text')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
